# (PART\*) Exercises {-}

# Exercise 1

In this section you'll be going through multiple challenges.
These will try to bring in everything you have learnt throughout the course.

Solutions are in the expandable boxes. Try your best to solve the challenge but use the solutions for help if you would like. Even if your solution works it can be good to check the solution as there are many ways to do the same thing in python.

This exercise will primarily focussed on the fundamentals you learnt in chapters 5 to 9.

Create a new notebook called __"07-Exercise_1"__ to carry out the below challenges.

__Tip__ The Appendix will be useful for quick lookup of various python __functions__, __methods__, etc..

## E1 challenge 1

Create a __markdown__ cell with the 1st level header "Exercise 1".

`r hide("E1C1 solution")`
```{python, eval=FALSE}
# Exercise 1
```
`r unhide()`

## E1 challenge 2

Carry out the following calculations with python.
Ensure each answer is displayed on your notebook.

1. Add 1 and 17.
2. Divide 17 by 6.
3. Subtract 9 from 5.
4. Multiply 0.1 by 60.
5. Find the remainder when dividing 7 by 0.6.

`r hide("E1C2 solution")`
```{python, eval=FALSE}
#E1C2.1
1+17
```
```{python, eval=FALSE}
#E1C2.2
17/6
```
```{python, eval=FALSE}
#E1C2.3
5-9
```
```{python, eval=FALSE}
#E1C2.4
0.1*60
```
```{python, eval=FALSE}
#E1C2.5
7%0.6
```
`r unhide()`

## E1 challenge 3

Write and run the below code to create some __variables__

```{python, eval=FALSE}
#Variables
fruit = "apples"
vegetable = "potatoes"
money = "POUNDS"
seven_int = 7
eight_string = "8"
```

Using these __variables__ __print__ out the below sentences. Ensure the __bold words__ are made with one or more of the above __variables__.

__Note__: Ensure you matching the case (upper/lower) of the sentences.

1. "I have __7__ __apples__ in a bushel".
2. "You have __8__ __POTATOES__ in a sack".
3. "We have __56__ __pounds__ in a wallet".

__Tip__: 8 * 7 = 56

`r hide("E1C3 solution")`
```{python, eval=FALSE}
#E1C3.1
print("I have " + str(seven_int) + " " + fruit + " in a bushel")
```
```{python, eval=FALSE}
#E1C3.2
print("You have " + eight_string + " " + vegetable.upper() + " in a sack")
```
```{python, eval=FALSE}
#E1C3.3
print("We have " + str(seven_int * int(eight_string)) + " " + money.lower() + " in a wallet")
```
`r unhide()`

## E1 challenge X

In this challenge you will create 3 __lists__ related to time.
The __variable names__ and contents of these __lists__ are:

1. __`hours`__: Numbers 1 to 9.
2. __`minutes`__: Number of minutes in 1 hour to 9 hours.
3. __`seconds`__: Number of seconds in 1 hour to 9 hours.

Once created __print__ all these __lists__.

__Note__: A __for loop__ will be useful to create `minutes` and `seconds` using the `hours` __list__.

`r hide("E1CX solution")`
```{python, eval=FALSE}
#X
hours = [1,2,3,4,5,6,7,8,9]
minutes = []
seconds = []
for hour in hours:
  minutes.append(hour * 60)
  seconds.append{hour * 60 * 60}
print(hours)
print(minutes)
print(seconds)
```
`r unhide()`